[Pipeline] stage
[Pipeline] { (MotioCI Login)
[Pipeline] withCredentials
10:52:39  Masking supported pattern matches of $CREDENTIALS_FILE
[Pipeline] {
[Pipeline] container
[Pipeline] {
[Pipeline] script
[Pipeline] {
[Pipeline] sh
10:52:40  + set -e
10:52:40  + cd MotioCI/api/CLI
10:52:40  ++ python3 ci-cli.py --server=https://cgrptmcip01.cloud.cammis.ca.gov --non-interactive login --credentialsFile ****
10:52:40  + TOKEN='Successfully loaded credentials from ****
10:52:40  == DEBUG: Attempting login with masked credentials ==
10:52:40  [{"instanceId": "1", "apiKey": "********"}]
10:52:40  == DEBUG: Sending masked credentials ==
10:52:40  [
10:52:40    {
10:52:40      "instanceId": "1",
10:52:40      "apiKey": "********"
10:52:40    }
10:52:40  ]
10:52:40  Error making request: HTTPSConnectionPool(host='\''cgrptmcip01.cloud.cammis.ca.gov'\'', port=443): Max retries exceeded with url: /api/login (Caused by NewConnectionError('\''<urllib3.connection.HTTPSConnection object at 0x7f743de2bd00>: Failed to establish a new connection: [Errno 111] Connection refused'\''))
10:52:40  Invalid parameters. Login cancelled!'
10:52:40  + echo 'Successfully loaded credentials from ****
10:52:40  == DEBUG: Attempting login with masked credentials ==
10:52:40  [{"instanceId": "1", "apiKey": "********"}]
10:52:40  == DEBUG: Sending masked credentials ==
10:52:40  [
10:52:40    {
10:52:40      "instanceId": "1",
10:52:40      "apiKey": "********"
10:52:40    }
10:52:40  ]
10:52:40  Error making request: HTTPSConnectionPool(host='\''cgrptmcip01.cloud.cammis.ca.gov'\'', port=443): Max retries exceeded with url: /api/login (Caused by NewConnectionError('\''<urllib3.connection.HTTPSConnection object at 0x7f743de2bd00>: Failed to establish a new connection: [Errno 111] Connection refused'\''))
10:52:40  Invalid parameters. Login cancelled!'
[Pipeline] echo
10:52:40  MotioCI login completed - token captured.
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Deploy)
[Pipeline] withCredentials
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] echo
10:52:40  Pipeline execution finished.
[Pipeline] echo
10:52:40  MotioCI pipeline failed.
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] End of Pipeline
ERROR: Could not find credentials entry with ID 'cognos-prod-service-user'

GitHub has been notified of this commitâ€™s build result

/var/lib/jenkins/jobs/Cognos Jobs/jobs/Cognos_deployment_pipeline/workspace/motioci-poctest@tmp/jfrog/70/.jfrog deleted
Finished: FAILURE
