[Pipeline] { (Dummy Deploy from DevTest to Prod)
[Pipeline] container
[Pipeline] {
[Pipeline] script
[Pipeline] {
[Pipeline] sh
13:56:00  + cd MotioCI/api/CLI
13:56:00  + python3 ci-cli.py --server=https://cgrptmcip01.cloud.cammis.ca.gov deploy --xauthtoken= --sourceInstanceName=Cognos-DEV/TEST --targetInstanceName=Cognos-PRD --projectName=Demo --targetLabelName=DummyDeployLabel --searchPath '/content/folder[@name='\''Motio Samples'\'']' --camPassportId=
13:56:00  Traceback (most recent call last):
13:56:00    File "/home/jenkins/agent/.local/lib/python3.9/site-packages/requests/models.py", line 910, in json
13:56:00      return complexjson.loads(self.text, **kwargs)
13:56:00    File "/usr/lib64/python3.9/json/__init__.py", line 346, in loads
13:56:00      return _default_decoder.decode(s)
13:56:00    File "/usr/lib64/python3.9/json/decoder.py", line 337, in decode
13:56:00      obj, end = self.raw_decode(s, idx=_w(s, 0).end())
13:56:00    File "/usr/lib64/python3.9/json/decoder.py", line 355, in raw_decode
13:56:00      raise JSONDecodeError("Expecting value", s, err.value) from None
13:56:00  json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
13:56:00  
13:56:00  During handling of the above exception, another exception occurred:
13:56:00  
13:56:00  Traceback (most recent call last):
13:56:00    File "/home/jenkins/agent/workspace/s_deployment_pipeline_newtesting/MotioCI/api/CLI/ci-cli.py", line 534, in <module>
13:56:00      run_deployment(args)
13:56:00    File "/home/jenkins/agent/workspace/s_deployment_pipeline_newtesting/MotioCI/api/CLI/ci-cli.py", line 244, in run_deployment
13:56:00      source_instance_id = find_instance_id(args.sourceInstanceId, args.sourceInstanceId,
13:56:00    File "/home/jenkins/agent/workspace/s_deployment_pipeline_newtesting/MotioCI/api/CLI/ci-cli.py", line 346, in find_instance_id
13:56:00      instance_array = instances.get_instances_default()
13:56:00    File "/home/jenkins/agent/workspace/s_deployment_pipeline_newtesting/MotioCI/api/CLI/instances.py", line 10, in get_instances_default
13:56:00      instance_array = response.json()["data"]["instances"]["edges"]
13:56:00    File "/home/jenkins/agent/.local/lib/python3.9/site-packages/requests/models.py", line 917, in json
13:56:00      raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
13:56:00  requests.exceptions.JSONDecodeError: [Errno Expecting value] : 0
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] echo
13:56:01  Pipeline execution finished.
[Pipeline] echo
13:56:01  MotioCI pipeline failed.
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] End of Pipeline
ERROR: script returned exit code 1

GitHub has been notified of this commitâ€™s build result

/var/lib/jenkins/jobs/Cognos Jobs/jobs/Cognos_deployment_pipeline/workspace/newtesting@tmp/jfrog/92/.jfrog deleted
Finished: FAILURE
